# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: <commit>
_src_path: <src>
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: None
author_name: None
cloud_provider: netlify
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: test_all_default_parameters_on_netlify
use_daisy_ui: true
use_eslint_prettier: true
use_github_actions: true
use_jest: true
use_playwright: true
use_tailwind: true

